/* butiDev — bilingual content (ES / EN) + config */

const WHATSAPP_PHONE = "573217449713";
const INSTAGRAM_URL = "https://instagram.com/butiDev";

const STACK = ["React", "Django", "Spring Boot", "Angular", "Node.js", "PostgreSQL", "TypeScript", "Vite", "Azure"];

const CONTENT = {
  es: {
    code: "ES",
    waMessage: "Hola butiDev 👋 Quiero contarles sobre mi caso y agendar un diagnóstico sin costo.",
    nav: [
      { id: "problema", label: "El problema" },
      { id: "porque", label: "Por qué" },
      { id: "servicios", label: "Servicios" },
      { id: "proyectos", label: "Proyectos" },
      { id: "proceso", label: "Proceso" },
      { id: "contacto", label: "Contacto" },
    ],
    navCta: "Hablemos",
    hero: {
      kicker: "Desarrollo de software a medida",
      title: ["Diagnóstico", "primero."],
      accent: "Código después.",
      subPre: "Construimos lo que tu negocio ",
      subStrong: "realmente",
      subPost: " necesita. Analizamos tu operación y construimos sin componentes innecesarios.",
      ctaPrimary: "Hablemos sin costo",
      ctaSecondary: "Ver proyectos",
      code: {
        file: "diagnostico.ts",
        c1: "// antes de escribir código",
        c2a: "const", c2b: " negocio = ", c2c: "analizar", c2d: "(operacion);",
        c4a: "if", c4b: " (negocio.", c4c: "necesita", c4d: ") {",
        c5: 'construir("solo lo esencial");',
        c6a: "} ", c6b: "// sin relleno",
        c8: "integrado a tu flujo",
      },
    },
    problem: {
      kicker: "El problema",
      title: ["Sistemas", "desconectados."],
      body: "La mayoría de negocios en crecimiento operan con procesos manuales que escalan mal y generan errores. Hojas de cálculo sueltas, tareas repetidas a mano, información que vive en cabezas y no en sistemas.",
      note: "// 3 sistemas que no se hablan = el triple de trabajo y el triple de errores.",
    },
    why: {
      kicker: "Por qué butiDev",
      title: "No somos otra fábrica de software.",
      reasons: [
        { title: "Diagnóstico primero. Código después.", desc: "Analizamos tu operación a fondo antes de escribir una sola línea. Construir sin entender es la forma más cara de equivocarse." },
        { title: "Sin componentes innecesarios.", desc: "Solo lo que tu negocio realmente necesita. Nada de funciones de relleno que nadie usa y que todos pagan." },
        { title: "Fidelidad total al diseño.", desc: "Pixel perfect a lo aprobado. Lo que ves en el Figma es exactamente lo que recibes en producción." },
        { title: "Tecnología integrada a tu flujo.", desc: "No construimos sistemas aislados. Lo que entregamos se conecta con tu operación, no la complica." },
      ],
    },
    services: {
      kicker: "Lo que hacemos",
      title: ["Tres formas de quitarte", "trabajo manual de encima."],
      infinity: "SIN LÍMITES",
      stackLabel: "Stack tecnológico",
      items: [
        { name: "Desarrollo de software a medida", desc: "Sistemas internos, ERPs, plataformas SaaS y herramientas que se adaptan a tu operación — no al revés.", points: ["Arquitectura a la medida", "Multi-tenant & roles", "Escalable desde el día uno"] },
        { name: "Desarrollo web", desc: "Sitios y aplicaciones web rápidas, responsive y fieles al diseño aprobado, listas para crecer contigo.", points: ["Responsive real", "Fiel al Figma", "Performance primero"] },
        { name: "Automatización de procesos", desc: "Eliminamos el trabajo manual repetitivo: cotizaciones, reportes, facturación y flujos que hoy te cuestan horas.", points: ["Menos errores", "Flujos end-to-end", "Integraciones a medida"] },
      ],
    },
    projects: {
      kicker: "Proyectos · Casos reales",
      title: ["Software que ya está", "trabajando en producción."],
      hint: "// click en cualquier proyecto para ver el caso completo →",
      open: "Ver caso",
      labelTag: "proyecto",
      detailLabel: "Lo destacado",
      stackLabel: "Stack tecnológico",
      modalCta: "Quiero algo así",
      items: [
        {
          name: "Gestión Inventarial de Droguerías", tag: "SaaS · Farmacias", type: "Sistema de gestión de inventario farmacéutico",
          stack: ["Spring Boot 3.2.5", "Angular 17", "Java 17", "PostgreSQL", "JWT"],
          highlights: ["Arquitectura multi-tenant para múltiples farmacias en una sola plataforma", "Event sourcing para trazabilidad total del stock en tiempo real"],
          detail: "Una plataforma SaaS donde cada farmacia opera de forma aislada y segura sobre la misma infraestructura. El control de inventario usa event sourcing: cada movimiento de stock queda registrado como un evento inmutable, lo que permite auditar y reconstruir el estado del inventario en cualquier momento.",
          features: ["Arquitectura multi-tenant con aislamiento por farmacia", "Event sourcing para el stock — trazabilidad completa", "RBAC con 3 roles diferenciados (admin, gestor, operador)", "Autenticación segura vía JWT"],
        },
        {
          name: "Saipan Airsoft Web", tag: "Blog · Comunidad", type: "Blog empresarial de comunidad airsoft",
          featured: true, image: "/assets/saipan-airsoft-hero.jpg",
          stack: ["React 19", "Vite", "Tailwind CSS", "TypeScript", "Vimeo Player"],
          highlights: ["Diseño 100% fiel al Figma aprobado, sin desviaciones", "Responsive impecable en 3 breakpoints, 9 secciones"],
          detail: "Un blog y portal de comunidad construido con fidelidad pixel-perfect al diseño aprobado en Figma. Nueve secciones cuidadosamente maquetadas, integración de video vía Vimeo Player y un comportamiento responsive verificado en tres breakpoints.",
          features: ["Fidelidad total al Figma aprobado", "9 secciones a la medida", "Responsive verificado en 3 breakpoints", "Reproducción de video integrada con Vimeo Player"],
        },
        {
          name: "Troqueles INK", tag: "ERP · Producción", type: "Sistema de cotizaciones y producción para artes gráficas",
          featured: true, image: "/assets/troqueles-ink-home.jpg",
          stack: ["Django", "DRF", "React 18", "WeasyPrint", "SQLite → PostgreSQL"],
          highlights: ["Calculadora de pliegos automática que elimina el cálculo manual", "Flujo completo cotización → factura, con PDF por correo"],
          detail: "Un ERP para una empresa de artes gráficas que automatiza desde la cotización hasta la factura. La calculadora de pliegos resuelve automáticamente el aprovechamiento del material, y cada documento se genera en PDF y se envía por correo sin intervención manual.",
          features: ["Calculadora de pliegos automática", "Generación de PDF con WeasyPrint y envío por correo", "Flujo end-to-end: cotización → producción → factura", "Migración de SQLite a PostgreSQL para escalar"],
        },
        {
          name: "F*cks News Poll", tag: "Real-time · Entretenimiento", type: "App de votación en tiempo real para shows de comedia en vivo",
          stack: ["React", "TypeScript", "Node.js/Express", "Azure SQL", "Azure App Service", "PWA"],
          highlights: ["2.000 usuarios concurrentes votando en vivo sin caídas", "Votación deduplicada por UUID — un voto por persona"],
          detail: "Una PWA de votación en tiempo real diseñada para shows de comedia en vivo, capaz de sostener 2.000 usuarios concurrentes. Los triggers a nivel de base de datos resuelven el conteo en O(1), y la deduplicación por UUID garantiza un voto único por asistente.",
          features: ["2.000 usuarios concurrentes en vivo", "Triggers en base de datos para conteo O(1)", "Votación deduplicada por UUID", "PWA desplegada sobre Azure App Service + Azure SQL"],
        },
      ],
    },
    process: {
      kicker: "Cómo trabajamos",
      title: ["Cuatro pasos. Cero", "sorpresas en el camino."],
      steps: [
        { n: "01", title: "Diagnóstico", desc: "Entendemos tu operación, tus cuellos de botella y qué te está costando tiempo." },
        { n: "02", title: "Propuesta", desc: "Definimos exactamente qué construir — y qué no. Alcance claro, sin sorpresas." },
        { n: "03", title: "Desarrollo", desc: "Iteramos contigo en ciclos cortos. Ves el avance, lo apruebas, seguimos." },
        { n: "04", title: "Entrega", desc: "Producto en producción, con documentación y soporte para que sigas solo." },
      ],
    },
    cta: {
      kicker: "Conversemos",
      title: ["¿Tu negocio está", "listo para escalar?"],
      sub: "Conversemos. Evaluamos tu caso sin costo y sin compromiso.",
      fName: "Tu nombre", fNamePh: "Ej. María Gómez",
      fContact: "Correo o Instagram", fContactPh: "hola@empresa.com  ·  @tunegocio",
      fCase: "¿Qué quieres resolver?", fCasePh: "Cuéntanos qué proceso te está costando tiempo hoy...",
      submit: "Contactar a butiDev",
      reassure: "Sin costo · Sin compromiso · Respuesta de una persona, no un bot",
      errName: "Cuéntanos cómo te llamas.",
      errContact: "Déjanos un correo o tu @ de Instagram.",
      errCase: "Cuéntanos un poco más sobre tu caso.",
      successTitle: "¡Listo,",
      successBody: "Recibimos tu caso. Te escribimos pronto para agendar el diagnóstico — sin costo. Mientras tanto, escríbenos también por WhatsApp o Instagram.",
      waBtn: "Escríbenos por WhatsApp",
    },
    footer: {
      tagline: "Diagnóstico primero. Código después. Soluciones tecnológicas a medida para empresas que quieren operar con eficiencia.",
      navLabel: "Navega", contactLabel: "Contacto",
      city: "Cali, Colombia",
      rights: "butiDev © 2025 · Cali, Colombia",
      madeWith: "Hecho sin componentes innecesarios.",
    },
  },

  en: {
    code: "EN",
    waMessage: "Hi butiDev 👋 I'd like to tell you about my case and book a free diagnosis.",
    nav: [
      { id: "problema", label: "The problem" },
      { id: "porque", label: "Why us" },
      { id: "servicios", label: "Services" },
      { id: "proyectos", label: "Projects" },
      { id: "proceso", label: "Process" },
      { id: "contacto", label: "Contact" },
    ],
    navCta: "Let's talk",
    hero: {
      kicker: "Custom software development",
      title: ["Diagnosis", "first."],
      accent: "Code after.",
      subPre: "We build what your business ",
      subStrong: "actually",
      subPost: " needs. We analyze your operation and build with no unnecessary components.",
      ctaPrimary: "Let's talk — free",
      ctaSecondary: "View projects",
      code: {
        file: "diagnosis.ts",
        c1: "// before writing any code",
        c2a: "const", c2b: " business = ", c2c: "analyze", c2d: "(operation);",
        c4a: "if", c4b: " (business.", c4c: "needsIt", c4d: ") {",
        c5: 'build("only the essential");',
        c6a: "} ", c6b: "// no filler",
        c8: "integrated into your flow",
      },
    },
    problem: {
      kicker: "The problem",
      title: ["Disconnected", "systems."],
      body: "Most growing businesses run on manual processes that scale badly and create errors. Loose spreadsheets, tasks repeated by hand, information that lives in people's heads instead of systems.",
      note: "// 3 systems that don't talk to each other = triple the work and triple the errors.",
    },
    why: {
      kicker: "Why butiDev",
      title: "We're not just another software shop.",
      reasons: [
        { title: "Diagnosis first. Code after.", desc: "We analyze your operation in depth before writing a single line. Building without understanding is the most expensive way to get it wrong." },
        { title: "No unnecessary components.", desc: "Only what your business actually needs. No filler features that nobody uses and everybody pays for." },
        { title: "Total fidelity to the design.", desc: "Pixel perfect to what was approved. What you see in Figma is exactly what you get in production." },
        { title: "Tech integrated into your flow.", desc: "We don't build isolated systems. What we deliver connects with your operation — it doesn't complicate it." },
      ],
    },
    services: {
      kicker: "What we do",
      title: ["Three ways to take manual", "work off your plate."],
      infinity: "NO LIMITS",
      stackLabel: "Tech stack",
      items: [
        { name: "Custom software development", desc: "Internal systems, ERPs, SaaS platforms and tools that adapt to your operation — not the other way around.", points: ["Architecture made to measure", "Multi-tenant & roles", "Scalable from day one"] },
        { name: "Web development", desc: "Fast, responsive web apps and sites, faithful to the approved design and ready to grow with you.", points: ["Truly responsive", "Faithful to Figma", "Performance first"] },
        { name: "Process automation", desc: "We remove repetitive manual work: quotes, reports, invoicing and flows that cost you hours today.", points: ["Fewer errors", "End-to-end flows", "Custom integrations"] },
      ],
    },
    projects: {
      kicker: "Projects · Real cases",
      title: ["Software already", "working in production."],
      hint: "// click any project to see the full case →",
      open: "View case",
      labelTag: "project",
      detailLabel: "The highlights",
      stackLabel: "Tech stack",
      modalCta: "I want something like this",
      items: [
        {
          name: "Pharmacy Inventory Management", tag: "SaaS · Pharmacies", type: "Pharmaceutical inventory management system",
          stack: ["Spring Boot 3.2.5", "Angular 17", "Java 17", "PostgreSQL", "JWT"],
          highlights: ["Multi-tenant architecture for multiple pharmacies on a single platform", "Event sourcing for full real-time stock traceability"],
          detail: "A SaaS platform where each pharmacy operates in an isolated, secure way on the same infrastructure. Inventory control uses event sourcing: every stock movement is recorded as an immutable event, which makes it possible to audit and reconstruct the inventory state at any point in time.",
          features: ["Multi-tenant architecture with per-pharmacy isolation", "Event sourcing for stock — complete traceability", "RBAC with 3 distinct roles (admin, manager, operator)", "Secure authentication via JWT"],
        },
        {
          name: "Saipan Airsoft Web", tag: "Blog · Community", type: "Corporate blog for an airsoft community",
          featured: true, image: "/assets/saipan-airsoft-hero.jpg",
          stack: ["React 19", "Vite", "Tailwind CSS", "TypeScript", "Vimeo Player"],
          highlights: ["100% faithful to the approved Figma, no deviations", "Flawless responsive across 3 breakpoints, 9 sections"],
          detail: "A blog and community portal built with pixel-perfect fidelity to the design approved in Figma. Nine carefully laid-out sections, video integration via Vimeo Player and responsive behavior verified across three breakpoints.",
          features: ["Total fidelity to the approved Figma", "9 bespoke sections", "Responsive verified across 3 breakpoints", "Integrated video playback with Vimeo Player"],
        },
        {
          name: "Troqueles INK", tag: "ERP · Production", type: "Quoting and production system for a graphic arts company",
          featured: true, image: "/assets/troqueles-ink-home.jpg",
          stack: ["Django", "DRF", "React 18", "WeasyPrint", "SQLite → PostgreSQL"],
          highlights: ["Automatic sheet calculator that eliminates manual math", "Full quote → invoice flow, with PDF by email"],
          detail: "An ERP for a graphic arts company that automates everything from quoting to invoicing. The sheet calculator automatically solves material yield, and every document is generated as a PDF and emailed without manual intervention.",
          features: ["Automatic sheet calculator", "PDF generation with WeasyPrint and email delivery", "End-to-end flow: quote → production → invoice", "Migration from SQLite to PostgreSQL to scale"],
        },
        {
          name: "F*cks News Poll", tag: "Real-time · Entertainment", type: "Real-time voting app for live comedy shows",
          stack: ["React", "TypeScript", "Node.js/Express", "Azure SQL", "Azure App Service", "PWA"],
          highlights: ["2,000 concurrent users voting live with no downtime", "Votes deduplicated by UUID — one vote per person"],
          detail: "A real-time voting PWA designed for live comedy shows, able to sustain 2,000 concurrent users. Database-level triggers resolve counting in O(1), and UUID deduplication guarantees a single vote per attendee.",
          features: ["2,000 concurrent users live", "Database triggers for O(1) counting", "Votes deduplicated by UUID", "PWA deployed on Azure App Service + Azure SQL"],
        },
      ],
    },
    process: {
      kicker: "How we work",
      title: ["Four steps. Zero", "surprises along the way."],
      steps: [
        { n: "01", title: "Diagnosis", desc: "We understand your operation, your bottlenecks and what's costing you time." },
        { n: "02", title: "Proposal", desc: "We define exactly what to build — and what not to. Clear scope, no surprises." },
        { n: "03", title: "Development", desc: "We iterate with you in short cycles. You see progress, approve it, we continue." },
        { n: "04", title: "Delivery", desc: "Product in production, with documentation and support so you can run on your own." },
      ],
    },
    cta: {
      kicker: "Let's talk",
      title: ["Is your business", "ready to scale?"],
      sub: "Let's talk. We assess your case at no cost and with no commitment.",
      fName: "Your name", fNamePh: "e.g. María Gómez",
      fContact: "Email or Instagram", fContactPh: "hi@company.com  ·  @yourbiz",
      fCase: "What do you want to solve?", fCasePh: "Tell us which process is costing you time today...",
      submit: "Contact butiDev",
      reassure: "No cost · No commitment · A reply from a person, not a bot",
      errName: "Tell us your name.",
      errContact: "Leave us an email or your Instagram @.",
      errCase: "Tell us a bit more about your case.",
      successTitle: "Done,",
      successBody: "We got your case. We'll write to you soon to book the diagnosis — at no cost. In the meantime, reach us on WhatsApp or Instagram too.",
      waBtn: "Message us on WhatsApp",
    },
    footer: {
      tagline: "Diagnosis first. Code after. Custom tech solutions for companies that want to operate efficiently.",
      navLabel: "Navigate", contactLabel: "Contact",
      city: "Cali, Colombia",
      rights: "butiDev © 2025 · Cali, Colombia",
      madeWith: "Built with no unnecessary components.",
    },
  },
};

export { CONTENT, STACK, WHATSAPP_PHONE, INSTAGRAM_URL };
